[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"

# API redirects
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA routing - catch all routes and serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
