import React from "react";

// Import all animations
import {
  WallPushups,
  InclinePushups,
  Squats,
  Crunches,
  Supermans,
  ArmCircles,
  DeclinePushups,
  JumpSquats,
  PikePushups,
  BulgarianSplitSquats,
  PlanksVariation,
  ClapPushups,
  ArcherPushups,
  PistolSquats,
  InvertedRows,
  HandstandPushups,
} from "@/components/animations/GymExercises";

import {
  Jab,
  Cross,
  JabCrossCombo,
  BasicFootwork,
  Hooks,
  Uppercuts,
  Slips,
  Pivots,
  JabCrossHookCombo,
  ComplexCombos,
  RollSlipCounter,
  FastShadowboxing,
  PowerCombinations,
} from "@/components/animations/BoxingExercises";

import {
  BasicSalsa,
  Merengue,
  Grapevine,
  SideSteps,
  Reggaeton,
  HipRolls,
  FastSyncopated,
  FullChoreography,
  ChildsPose,
  CatCow,
  CobraPose,
  DownwardDog,
  WarriorII,
  BridgePose,
  TrianglePose,
  PlankFlow,
  CrowPose,
  HandstandPrep,
  NeckStretch,
  QuadStretch,
  HamstringReach,
  DeepLungeStretch,
  ThoracicRotation,
  Splits,
  DeepBackbend,
  ArmSwingsWarmup,
  MarchingWarmup,
  HighKneesWarmup,
  JumpingJacksWarmup,
  SkaterHopsWarmup,
  BurpeeWarmupExercise,
} from "@/components/animations/DanceAndFlexibilityExercises";

export interface WorkoutExercise {
  id: string;
  title: string;
  category: "gym" | "boxing" | "zumba" | "yoga" | "stretching" | "warmups";
  level: "beginner" | "intermediate" | "advanced";
  muscleGroup: string | null;
  duration_minutes: number;
  calories_burned: number;
  variationNumber: number;
  animationComponent: React.ComponentType<any>;
  description: string;
}

// Workout exercises registry
const workoutExercises: WorkoutExercise[] = [
  // ===== GYM - BEGINNER =====
  {
    id: "gym-beginner-wall-pushups-1",
    title: "Wall Pushups",
    category: "gym",
    level: "beginner",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 50,
    variationNumber: 1,
    animationComponent: WallPushups,
    description: "Beginner-friendly pushups against a wall for chest strength",
  },
  {
    id: "gym-beginner-incline-pushups-2",
    title: "Incline Pushups",
    category: "gym",
    level: "beginner",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 60,
    variationNumber: 2,
    animationComponent: InclinePushups,
    description: "Pushups on an inclined surface for progressive training",
  },
  {
    id: "gym-beginner-squats-3",
    title: "Bodyweight Squats",
    category: "gym",
    level: "beginner",
    muscleGroup: "legs",
    duration_minutes: 20,
    calories_burned: 80,
    variationNumber: 3,
    animationComponent: Squats,
    description: "Basic squats to strengthen legs and glutes",
  },
  {
    id: "gym-beginner-crunches-4",
    title: "Crunches",
    category: "gym",
    level: "beginner",
    muscleGroup: "abs",
    duration_minutes: 10,
    calories_burned: 40,
    variationNumber: 4,
    animationComponent: Crunches,
    description: "Core strengthening exercise for abdominal muscles",
  },
  {
    id: "gym-beginner-supermans-1",
    title: "Superman Exercise",
    category: "gym",
    level: "beginner",
    muscleGroup: "back",
    duration_minutes: 12,
    calories_burned: 45,
    variationNumber: 1,
    animationComponent: Supermans,
    description: "Back strengthening exercise targeting posterior chain",
  },
  {
    id: "gym-beginner-arm-circles-2",
    title: "Arm Circles",
    category: "gym",
    level: "beginner",
    muscleGroup: "shoulders",
    duration_minutes: 8,
    calories_burned: 30,
    variationNumber: 2,
    animationComponent: ArmCircles,
    description: "Shoulder mobility and warm-up exercise",
  },

  // ===== GYM - INTERMEDIATE =====
  {
    id: "gym-intermediate-decline-pushups-1",
    title: "Decline Pushups",
    category: "gym",
    level: "intermediate",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 75,
    variationNumber: 1,
    animationComponent: DeclinePushups,
    description: "Advanced pushup variation with increased difficulty",
  },
  {
    id: "gym-intermediate-jump-squats-2",
    title: "Jump Squats",
    category: "gym",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 20,
    calories_burned: 120,
    variationNumber: 2,
    animationComponent: JumpSquats,
    description: "Explosive leg exercise combining cardio and strength",
  },
  {
    id: "gym-intermediate-pike-pushups-3",
    title: "Pike Pushups",
    category: "gym",
    level: "intermediate",
    muscleGroup: "shoulders",
    duration_minutes: 15,
    calories_burned: 70,
    variationNumber: 3,
    animationComponent: PikePushups,
    description: "Shoulder-focused pushup variation",
  },
  {
    id: "gym-intermediate-bulgarian-split-1",
    title: "Bulgarian Split Squats",
    category: "gym",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 20,
    calories_burned: 100,
    variationNumber: 1,
    animationComponent: BulgarianSplitSquats,
    description: "Single-leg focused squat variation",
  },
  {
    id: "gym-intermediate-planks-variation-1",
    title: "Plank Variations",
    category: "gym",
    level: "intermediate",
    muscleGroup: "abs",
    duration_minutes: 12,
    calories_burned: 55,
    variationNumber: 1,
    animationComponent: PlanksVariation,
    description: "Core isometric hold with multiple variations",
  },

  // ===== GYM - ADVANCED =====
  {
    id: "gym-advanced-clap-pushups-1",
    title: "Clap Pushups",
    category: "gym",
    level: "advanced",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 90,
    variationNumber: 1,
    animationComponent: ClapPushups,
    description: "Explosive pushup with clap for advanced strength training",
  },
  {
    id: "gym-advanced-archer-pushups-2",
    title: "Archer Pushups",
    category: "gym",
    level: "advanced",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 85,
    variationNumber: 2,
    animationComponent: ArcherPushups,
    description: "Unilateral pushup progression toward one-armed pushups",
  },
  {
    id: "gym-advanced-pistol-squats-3",
    title: "Pistol Squats",
    category: "gym",
    level: "advanced",
    muscleGroup: "legs",
    duration_minutes: 20,
    calories_burned: 110,
    variationNumber: 3,
    animationComponent: PistolSquats,
    description: "Single-leg squat for extreme leg strength",
  },
  {
    id: "gym-advanced-inverted-rows-4",
    title: "Inverted Rows",
    category: "gym",
    level: "advanced",
    muscleGroup: "back",
    duration_minutes: 15,
    calories_burned: 80,
    variationNumber: 4,
    animationComponent: InvertedRows,
    description: "Advanced horizontal pulling exercise",
  },
  {
    id: "gym-advanced-handstand-pushups-1",
    title: "Handstand Pushup Progressions",
    category: "gym",
    level: "advanced",
    muscleGroup: "shoulders",
    duration_minutes: 20,
    calories_burned: 100,
    variationNumber: 1,
    animationComponent: HandstandPushups,
    description: "Advanced shoulder exercise with handstand variation",
  },

  // ===== BOXING - BEGINNER =====
  {
    id: "boxing-beginner-jab-1",
    title: "Jab",
    category: "boxing",
    level: "beginner",
    muscleGroup: "shoulders",
    duration_minutes: 15,
    calories_burned: 75,
    variationNumber: 1,
    animationComponent: Jab,
    description: "Basic straight punch from the lead hand",
  },
  {
    id: "boxing-beginner-cross-2",
    title: "Cross",
    category: "boxing",
    level: "beginner",
    muscleGroup: "chest",
    duration_minutes: 15,
    calories_burned: 80,
    variationNumber: 2,
    animationComponent: Cross,
    description: "Power punch from the rear hand",
  },
  {
    id: "boxing-beginner-jab-cross-combo-3",
    title: "Jab-Cross Combo",
    category: "boxing",
    level: "beginner",
    muscleGroup: "arms",
    duration_minutes: 15,
    calories_burned: 85,
    variationNumber: 3,
    animationComponent: JabCrossCombo,
    description: "Basic two-punch combination",
  },
  {
    id: "boxing-beginner-footwork-4",
    title: "Basic Footwork",
    category: "boxing",
    level: "beginner",
    muscleGroup: "legs",
    duration_minutes: 15,
    calories_burned: 70,
    variationNumber: 4,
    animationComponent: BasicFootwork,
    description: "Fundamental stance and foot movement",
  },

  // ===== BOXING - INTERMEDIATE =====
  {
    id: "boxing-intermediate-hooks-1",
    title: "Hooks",
    category: "boxing",
    level: "intermediate",
    muscleGroup: "shoulders",
    duration_minutes: 15,
    calories_burned: 85,
    variationNumber: 1,
    animationComponent: Hooks,
    description: "Curved punches targeting sides of opponent",
  },
  {
    id: "boxing-intermediate-uppercuts-2",
    title: "Uppercuts",
    category: "boxing",
    level: "intermediate",
    muscleGroup: "arms",
    duration_minutes: 15,
    calories_burned: 85,
    variationNumber: 2,
    animationComponent: Uppercuts,
    description: "Upward punches from below",
  },
  {
    id: "boxing-intermediate-slips-3",
    title: "Slips",
    category: "boxing",
    level: "intermediate",
    muscleGroup: "back",
    duration_minutes: 15,
    calories_burned: 70,
    variationNumber: 3,
    animationComponent: Slips,
    description: "Head movement defense technique",
  },
  {
    id: "boxing-intermediate-pivots-4",
    title: "Pivots",
    category: "boxing",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 15,
    calories_burned: 75,
    variationNumber: 4,
    animationComponent: Pivots,
    description: "Rotational footwork for positioning",
  },
  {
    id: "boxing-intermediate-jab-cross-hook-1",
    title: "Jab-Cross-Hook Combo",
    category: "boxing",
    level: "intermediate",
    muscleGroup: "arms",
    duration_minutes: 20,
    calories_burned: 100,
    variationNumber: 1,
    animationComponent: JabCrossHookCombo,
    description: "Three-punch combination",
  },

  // ===== BOXING - ADVANCED =====
  {
    id: "boxing-advanced-complex-combos-1",
    title: "Complex Combos (1-2-3-2)",
    category: "boxing",
    level: "advanced",
    muscleGroup: "arms",
    duration_minutes: 20,
    calories_burned: 120,
    variationNumber: 1,
    animationComponent: ComplexCombos,
    description: "Advanced multi-punch combination sequences",
  },
  {
    id: "boxing-advanced-roll-slip-counter-2",
    title: "Roll-Slip Counter",
    category: "boxing",
    level: "advanced",
    muscleGroup: "back",
    duration_minutes: 20,
    calories_burned: 110,
    variationNumber: 2,
    animationComponent: RollSlipCounter,
    description: "Defense with immediate counter-attack",
  },
  {
    id: "boxing-advanced-shadowboxing-3",
    title: "Fast Shadowboxing",
    category: "boxing",
    level: "advanced",
    muscleGroup: "arms",
    duration_minutes: 20,
    calories_burned: 115,
    variationNumber: 3,
    animationComponent: FastShadowboxing,
    description: "High-speed boxing practice without opponent",
  },
  {
    id: "boxing-advanced-power-combos-4",
    title: "Power Combinations",
    category: "boxing",
    level: "advanced",
    muscleGroup: "chest",
    duration_minutes: 20,
    calories_burned: 125,
    variationNumber: 4,
    animationComponent: PowerCombinations,
    description: "Heavy, powerful multi-punch sequences",
  },

  // ===== ZUMBA - BEGINNER =====
  {
    id: "zumba-beginner-salsa-1",
    title: "Basic Salsa",
    category: "zumba",
    level: "beginner",
    muscleGroup: null,
    duration_minutes: 20,
    calories_burned: 100,
    variationNumber: 1,
    animationComponent: BasicSalsa,
    description: "Fundamental salsa dance steps",
  },
  {
    id: "zumba-beginner-merengue-2",
    title: "Merengue",
    category: "zumba",
    level: "beginner",
    muscleGroup: null,
    duration_minutes: 20,
    calories_burned: 95,
    variationNumber: 2,
    animationComponent: Merengue,
    description: "Basic merengue rhythm and steps",
  },
  {
    id: "zumba-beginner-grapevine-3",
    title: "Grapevine",
    category: "zumba",
    level: "beginner",
    muscleGroup: null,
    duration_minutes: 15,
    calories_burned: 85,
    variationNumber: 3,
    animationComponent: Grapevine,
    description: "Lateral stepping pattern in dance",
  },
  {
    id: "zumba-beginner-side-steps-4",
    title: "Side Steps",
    category: "zumba",
    level: "beginner",
    muscleGroup: null,
    duration_minutes: 15,
    calories_burned: 80,
    variationNumber: 4,
    animationComponent: SideSteps,
    description: "Basic side-to-side movement",
  },

  // ===== ZUMBA - INTERMEDIATE =====
  {
    id: "zumba-intermediate-reggaeton-1",
    title: "Reggaeton Steps",
    category: "zumba",
    level: "intermediate",
    muscleGroup: null,
    duration_minutes: 20,
    calories_burned: 110,
    variationNumber: 1,
    animationComponent: Reggaeton,
    description: "Hip-hop influenced reggaeton movements",
  },
  {
    id: "zumba-intermediate-hip-rolls-2",
    title: "Hip Rolls",
    category: "zumba",
    level: "intermediate",
    muscleGroup: null,
    duration_minutes: 20,
    calories_burned: 100,
    variationNumber: 2,
    animationComponent: HipRolls,
    description: "Rhythmic hip isolation movements",
  },
  {
    id: "zumba-intermediate-fast-synco-3",
    title: "Faster Syncopated Moves",
    category: "zumba",
    level: "intermediate",
    muscleGroup: null,
    duration_minutes: 25,
    calories_burned: 125,
    variationNumber: 3,
    animationComponent: FastSyncopated,
    description: "Complex rhythmic movement patterns",
  },

  // ===== ZUMBA - ADVANCED =====
  {
    id: "zumba-advanced-choreography-1",
    title: "Full Choreography",
    category: "zumba",
    level: "advanced",
    muscleGroup: null,
    duration_minutes: 30,
    calories_burned: 150,
    variationNumber: 1,
    animationComponent: FullChoreography,
    description: "Complete choreographed dance routine",
  },

  // ===== YOGA - BEGINNER =====
  {
    id: "yoga-beginner-childs-1",
    title: "Child's Pose",
    category: "yoga",
    level: "beginner",
    muscleGroup: "back",
    duration_minutes: 10,
    calories_burned: 20,
    variationNumber: 1,
    animationComponent: ChildsPose,
    description: "Restful yoga pose for relaxation",
  },
  {
    id: "yoga-beginner-cat-cow-2",
    title: "Cat-Cow",
    category: "yoga",
    level: "beginner",
    muscleGroup: "back",
    duration_minutes: 10,
    calories_burned: 25,
    variationNumber: 2,
    animationComponent: CatCow,
    description: "Spinal mobility and warm-up sequence",
  },
  {
    id: "yoga-beginner-cobra-3",
    title: "Cobra Pose",
    category: "yoga",
    level: "beginner",
    muscleGroup: "chest",
    duration_minutes: 12,
    calories_burned: 30,
    variationNumber: 3,
    animationComponent: CobraPose,
    description: "Backbend pose for chest and core",
  },
  {
    id: "yoga-beginner-downward-dog-4",
    title: "Downward Dog",
    category: "yoga",
    level: "beginner",
    muscleGroup: "hamstrings",
    duration_minutes: 12,
    calories_burned: 35,
    variationNumber: 4,
    animationComponent: DownwardDog,
    description: "Fundamental inversion pose",
  },

  // ===== YOGA - INTERMEDIATE =====
  {
    id: "yoga-intermediate-warrior-1",
    title: "Warrior II",
    category: "yoga",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 15,
    calories_burned: 45,
    variationNumber: 1,
    animationComponent: WarriorII,
    description: "Standing strength pose with arm extension",
  },
  {
    id: "yoga-intermediate-bridge-2",
    title: "Bridge Pose",
    category: "yoga",
    level: "intermediate",
    muscleGroup: "glutes",
    duration_minutes: 12,
    calories_burned: 40,
    variationNumber: 2,
    animationComponent: BridgePose,
    description: "Glute and core strengthening pose",
  },
  {
    id: "yoga-intermediate-triangle-3",
    title: "Triangle Pose",
    category: "yoga",
    level: "intermediate",
    muscleGroup: "hamstrings",
    duration_minutes: 15,
    calories_burned: 40,
    variationNumber: 3,
    animationComponent: TrianglePose,
    description: "Side stretch and balance pose",
  },
  {
    id: "yoga-intermediate-plank-flow-4",
    title: "Plank Flow",
    category: "yoga",
    level: "intermediate",
    muscleGroup: "abs",
    duration_minutes: 15,
    calories_burned: 50,
    variationNumber: 4,
    animationComponent: PlankFlow,
    description: "Dynamic core strengthening flow",
  },

  // ===== YOGA - ADVANCED =====
  {
    id: "yoga-advanced-crow-1",
    title: "Crow Pose",
    category: "yoga",
    level: "advanced",
    muscleGroup: "arms",
    duration_minutes: 15,
    calories_burned: 50,
    variationNumber: 1,
    animationComponent: CrowPose,
    description: "Advanced arm balance pose",
  },
  {
    id: "yoga-advanced-handstand-prep-2",
    title: "Handstand Prep",
    category: "yoga",
    level: "advanced",
    muscleGroup: "shoulders",
    duration_minutes: 20,
    calories_burned: 60,
    variationNumber: 2,
    animationComponent: HandstandPrep,
    description: "Progression toward full handstand",
  },

  // ===== STRETCHING - BEGINNER =====
  {
    id: "stretching-beginner-neck-1",
    title: "Neck Stretch",
    category: "stretching",
    level: "beginner",
    muscleGroup: "neck",
    duration_minutes: 5,
    calories_burned: 10,
    variationNumber: 1,
    animationComponent: NeckStretch,
    description: "Gentle neck mobility exercise",
  },
  {
    id: "stretching-beginner-quad-2",
    title: "Quad Stretch",
    category: "stretching",
    level: "beginner",
    muscleGroup: "legs",
    duration_minutes: 8,
    calories_burned: 15,
    variationNumber: 2,
    animationComponent: QuadStretch,
    description: "Front thigh flexibility exercise",
  },
  {
    id: "stretching-beginner-hamstring-3",
    title: "Hamstring Reach",
    category: "stretching",
    level: "beginner",
    muscleGroup: "hamstrings",
    duration_minutes: 8,
    calories_burned: 15,
    variationNumber: 3,
    animationComponent: HamstringReach,
    description: "Back thigh flexibility exercise",
  },

  // ===== STRETCHING - INTERMEDIATE =====
  {
    id: "stretching-intermediate-deep-lunge-1",
    title: "Deep Lunge Stretch",
    category: "stretching",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 12,
    calories_burned: 25,
    variationNumber: 1,
    animationComponent: DeepLungeStretch,
    description: "Advanced leg and hip flexor stretch",
  },
  {
    id: "stretching-intermediate-thoracic-2",
    title: "Thoracic Rotation",
    category: "stretching",
    level: "intermediate",
    muscleGroup: "back",
    duration_minutes: 10,
    calories_burned: 20,
    variationNumber: 2,
    animationComponent: ThoracicRotation,
    description: "Upper back mobility and rotation",
  },

  // ===== STRETCHING - ADVANCED =====
  {
    id: "stretching-advanced-splits-1",
    title: "Splits",
    category: "stretching",
    level: "advanced",
    muscleGroup: "hamstrings",
    duration_minutes: 15,
    calories_burned: 35,
    variationNumber: 1,
    animationComponent: Splits,
    description: "Advanced full-body flexibility",
  },
  {
    id: "stretching-advanced-backbend-2",
    title: "Deep Backbend",
    category: "stretching",
    level: "advanced",
    muscleGroup: "back",
    duration_minutes: 15,
    calories_burned: 40,
    variationNumber: 2,
    animationComponent: DeepBackbend,
    description: "Advanced back and shoulder flexibility",
  },

  // ===== WARMUPS - BEGINNER =====
  {
    id: "warmups-beginner-arm-swings-1",
    title: "Arm Swings",
    category: "warmups",
    level: "beginner",
    muscleGroup: "shoulders",
    duration_minutes: 5,
    calories_burned: 15,
    variationNumber: 1,
    animationComponent: ArmSwingsWarmup,
    description: "Shoulder mobility warm-up",
  },
  {
    id: "warmups-beginner-marching-2",
    title: "Marching",
    category: "warmups",
    level: "beginner",
    muscleGroup: "legs",
    duration_minutes: 5,
    calories_burned: 20,
    variationNumber: 2,
    animationComponent: MarchingWarmup,
    description: "Low-impact cardio warm-up",
  },

  // ===== WARMUPS - INTERMEDIATE =====
  {
    id: "warmups-intermediate-high-knees-1",
    title: "High Knees",
    category: "warmups",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 8,
    calories_burned: 40,
    variationNumber: 1,
    animationComponent: HighKneesWarmup,
    description: "Cardio warm-up with leg elevation",
  },
  {
    id: "warmups-intermediate-jumping-jacks-2",
    title: "Jumping Jacks",
    category: "warmups",
    level: "intermediate",
    muscleGroup: "legs",
    duration_minutes: 8,
    calories_burned: 45,
    variationNumber: 2,
    animationComponent: JumpingJacksWarmup,
    description: "Classic full-body warm-up",
  },

  // ===== WARMUPS - ADVANCED =====
  {
    id: "warmups-advanced-skater-hops-1",
    title: "Skater Hops",
    category: "warmups",
    level: "advanced",
    muscleGroup: "legs",
    duration_minutes: 10,
    calories_burned: 65,
    variationNumber: 1,
    animationComponent: SkaterHopsWarmup,
    description: "High-intensity lateral jumping warm-up",
  },
  {
    id: "warmups-advanced-burpees-2",
    title: "Burpee Warm-up",
    category: "warmups",
    level: "advanced",
    muscleGroup: "legs",
    duration_minutes: 10,
    calories_burned: 75,
    variationNumber: 2,
    animationComponent: BurpeeWarmupExercise,
    description: "Full-body explosive warm-up",
  },
];

export const getWorkoutsByCategory = (
  category: "gym" | "boxing" | "zumba" | "yoga" | "stretching" | "warmups",
) => workoutExercises.filter((w) => w.category === category);

export const getWorkoutsByLevel = (
  level: "beginner" | "intermediate" | "advanced",
) => workoutExercises.filter((w) => w.level === level);

export const getWorkoutsByCategoryAndLevel = (
  category: "gym" | "boxing" | "zumba" | "yoga" | "stretching" | "warmups",
  level: "beginner" | "intermediate" | "advanced",
) =>
  workoutExercises.filter((w) => w.category === category && w.level === level);

export const getWorkoutById = (id: string) =>
  workoutExercises.find((w) => w.id === id);

export default workoutExercises;
